name: Java cd on github hosted runners server for deployment

concurrency: production

on:
  push:
    branches:
      - MVP
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy

build:
  # The type of runner that the job will run on
  runs-on: ubuntu-latest